JmeMainBundle_default:
      pattern: /
      defaults:  { _controller: JmeArticleBundle:Default:latest}

JmeMainBundle_homepage:
      locales:   { fi: /fi, en: /en }
      defaults:  { _controller: JmeMainBundle:Default:index}

JmeMainBundle_projects:
      locales:   { fi: /projektit, en: /projects }
      defaults:  { _controller: JmeMainBundle:Default:projects}

login_check:
    pattern: /login_check

login_success:
    pattern: /login_success
    defaults:  { _controller: JmeMainBundle:Default:index}

jme_login:
    locales: {fi: /kirjaudu, en: /login}
    defaults:  { _controller: JmeMainBundle:Security:login }

jme_dialog_delete:
    locales: {en: /en/dialog/delete, fi: /fi/dialog/poista}
    defaults: {_controller: XiDialogBundle:Dialog:delete}