JmeMainBundle_default:
      pattern: /
      defaults:  { _controller: JmeArticleBundle:Default:latest}

JmeMainBundle_homepage:
      locales:   { fi: /fi, en: /en }
      defaults:  { _controller: JmeMainBundle:Default:index}

login_check:
    pattern: /login_check

login_success:
    pattern: /login_success
    defaults:  { _controller: JmeMainBundle:Default:index}

jme_login:
    locales: {fi: /kirjaudu, en: /login}
    defaults:  { _controller: JmeMainBundle:Security:login }