JmeMainBundle_default:
      pattern: /
      defaults:  { _controller: JmeArticleBundle:Default:latest}

JmeMainBundle_projects:
      pattern: "/projects"
      defaults:  { _controller: JmeMainBundle:Default:projects}

JmeMainBundle_about:
      pattern: "/about"
      defaults:  { _controller: JmeMainBundle:Default:about}

login_check:
    pattern: /login_check

login_success:
    pattern: /login_success
    defaults:  { _controller: JmeMainBundle:Default:index}

jme_login:
    pattern: "/login"
    defaults:  { _controller: JmeUserBundle:Security:login }

jme_dialog_delete:
    pattern: "/dialog/delete"
    defaults: {_controller: XiDialogBundle:Dialog:delete}

jme_post_test:
    pattern: "/api/v1/notes"
    defaults:  { _controller: JmeMainBundle:Default:createNotes}
    requirements: { _method: post }

jme_get_test:
    pattern: "/api/v1/notes"
    defaults:  { _controller: JmeMainBundle:Default:notes}
    requirements: { _method: get }