imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: fi }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'], assets_version: 1337 }
    default_locale:  %locale%
    trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'XiTagBundle:Form:tag-fields.html.twig'
    globals:
        domain:   %domain%


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    bundles: ["JmeArticleBundle", "JmeMainBundle", "XiSelectorBundle", "XiTagBundle"]
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        less:
            node:       %node_bin%
            node_paths: [%kernel.root_dir%/../node_modules]
            apply_to: "\.less$"
        coffee:
            bin:  %kernel.root_dir%/../node_modules/coffee-script/bin/coffee
            node: %node_bin%
            apply_to: "\.coffee$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true



# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

be_simple_i18n_routing: ~

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Jme\MainBundle\Entity\User



stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            sluggable:     true


fpn_tag:
    model:
        tag_class:     Xi\Bundle\TagBundle\Entity\Tag
        tagging_class: Xi\Bundle\TagBundle\Entity\Tagging