JmeArticleBundle:
    resource: "@JmeArticleBundle/Resources/config/routing.yml"
    prefix:   /
    type: be_simple_i18n

JmeMainBundle:
    resource: "@JmeMainBundle/Resources/config/routing.yml"
    prefix: /
    type: be_simple_i18n

_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

XiTagBundle:
    resource: "@XiTagBundle/Resources/config/routing.yml"
    prefix:   /

fos_comment_api:
    type: rest
    resource: "@JmeCommentBundle/Resources/config/routing.yml"
    prefix: /comments-api
    defaults: { _format: html }

