jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path:  /login
                check_path:  /login_check
                always_use_default_target_path: true
                default_target_path:            /
                use_referer:                    false
                failure_path:                   /login

            logout:
                target: /
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - {path: ^/(article/new),             role: IS_AUTHENTICATED_FULLY}
        - {path: ^/(article/edit),     role: IS_AUTHENTICATED_FULLY}
        - {path: ^/(article/update),   role: IS_AUTHENTICATED_FULLY}
        - {path: ^/(article/remove),    role: IS_AUTHENTICATED_FULLY}

        - { path: ^/(en|fi)$,                                        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,                                           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check,                                     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(register),                 role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,                               role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout,                                          role: IS_AUTHENTICATED_FULLY       }
        - { path: /media,                                            role: IS_AUTHENTICATED_FULLY       }


