jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        encode_as_base64: false
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      fos_userbundle:
        id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                always_use_default_target_path: false
                default_target_path:            /login_success
                use_referer:                    false
            logout:
                target: /%locale%
            anonymous:  true

    access_control:
        - { path: ^/(en|fi)$,                                         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,                                            role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check,                                      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout,                                           role: IS_AUTHENTICATED_FULLY       }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN:  ROLE_ADMIN