services:
    jme_media.repository.media:
        class: Jme\MediaBundle\Repository\MediaRepository
        arguments: [Jme\MediaBundle\Entity\File]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository

    jme_media.service.media:
        class:     Jme\MediaBundle\Service\MediaService
        arguments: ["@xi_filelib", "@jme_media.repository.media", "@xi_filelib.publisher"]