
jme_article_latest:
    pattern: /
    defaults: { _controller: JmeArticleBundle:Default:latest }

jme_article_new:
    pattern: "/article/new"
    defaults: { _controller: JmeArticleBundle:Default:new }

jme_article_create:
    pattern: "/article/new"
    defaults: { _controller: JmeArticleBundle:Default:create }
    requirements: {_method: post}

jme_article_edit:
    pattern: "/article/edit/{article}"
    defaults: { _controller: JmeArticleBundle:Default:edit }
    requirements: {_method: get, article:  \d+}

jme_article_update:
    pattern: "/article/update/{article}"
    defaults: { _controller: JmeArticleBundle:Default:update }
    requirements: {_method: post, article:  \d+}

jme_article_view:
    pattern: "/article/{article}"
    defaults: { _controller: JmeArticleBundle:Default:view }
    requirements: { _method: get, article:  \d+ }

jme_article_remove:
    pattern: "/article/remove/{article}"
    defaults: { _controller: JmeArticleBundle:Default:remove }
    requirements: { _method: get, article:  \d+ }