parameters:
#    jme_article.example.class: Jme\ArticleBundle\Example

services:
  jme_article.service.article:
          class:     Jme\ArticleBundle\Service\ArticleService
          arguments: ["@doctrine.orm.entity_manager"]
