parameters:
#    jme_article.example.class: Jme\ArticleBundle\Example

services:
#    jme_article.example:
#        class: %jme_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
