---
- hosts: all
  user: vagrant
  sudo: true
  vars:
    web_server: nginxphp
    servername: janimattiellonen.localhost 192.168.111.99
    timezone: Europe/Helsinki
    app_name: website
    web_root: '/vagrant/web'
  vars_files:
    - vars/mariadb.yml
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - nginx
    - nginx-vhost
    - php5-fpm
    - mariadb
    - composer
    - phpcommon
    - app
